@startuml
title <size:24>TaskBackEndApplication</size>

set separator none
top to bottom direction

<style>
  root {
    BackgroundColor: #ffffff
    FontColor: #444444
  }
</style>

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

System_Boundary("TaskBackEndApplication_boundary", "TaskBackEndApplication", $tags="") {
  Container_Boundary("TaskBackEndApplication.TaskBackEndApplication_boundary", "TaskBackEndApplication", $tags="") {
    Component(TaskBackEndApplication.TaskBackEndApplication.Task, "Task", $techn="Module", $descr="", $tags="", $link="")
    Component(TaskBackEndApplication.TaskBackEndApplication.Template, "Template", $techn="Module", $descr="", $tags="", $link="")
  }

}

Rel(TaskBackEndApplication.TaskBackEndApplication.Template, TaskBackEndApplication.TaskBackEndApplication.Task, "uses", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
hide stereotypes
@enduml